VARIABLE = "var"
IF = "if"
WHILE = "while"
ASSIGNMENT = "="
ADD = "+"
SUBTRACT = "-"
MULTIPLY = "*"
DIVIDE = "/"
MODULO = "%"
PRINT = "print"
ALL = [VARIABLE, IF, WHILE, ASSIGNMENT, ADD, SUBTRACT, DIVIDE, MODULO, PRINT]
MATH_KEYWORDS = [ADD, SUBTRACT, MULTIPLY, DIVIDE, MODULO]
FUNCTIONAL_KEYWORDS = [IF, WHILE, PRINT]
