VARIABLE = "var"
IF = "if"
WHILE = "while"
ASSIGNMENT = "="
ADDITION = "+"
SUBTRACTION = "-"
DIVIDE = "/"
MODULO = "%"
PRINT = "print"
ALL = [VARIABLE, IF, WHILE, ASSIGNMENT, ADDITION, SUBTRACTION, DIVIDE, MODULO, PRINT]
MATH_KEYWORDS = [ADDITION, SUBTRACTION, DIVIDE, MODULO]
FUNCTIONAL_KEYWORDS = [IF, WHILE, PRINT]
